name: dbt Main Deployment

on:
  push:
    branches:
      - main   # 👈 trigger only when pushing to main

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dbt
        run: |
          pip install dbt-duckdb

      - name: Run dbt debug
        run: dbt debug

      - name: Run dbt models
        run: dbt run