name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dbt
        run: pip install dbt-duckdb

      - name: Run dbt in DEV
        if: github.ref == 'refs/heads/dev'
        run: dbt build --target dev

      - name: Run dbt in STAGING
        if: github.ref == 'refs/heads/staging'
        run: dbt build --target staging

      - name: Run dbt in PROD
        if: github.ref == 'refs/heads/main'
        run: dbt build --target prod